CUSTOM_MATRIX = lite

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
STENO_ENABLE = no
NKRO_ENABLE = no
MOUSEKEY_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
OS_DETECTION_ENABLE = yes

CUSTOM_KEYCODE = no
SERIAL_DRIVER = vendor
KEYBOARD_SHARED_EP = yes

RGBLIGHT_ENABLE = no   # Enable keyboard RGB underglow

RGB_MATRIX_ENABLE = no   # Enable keyboard RGB per key

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_TRANSPORT = i2c
WPM_ENABLE = yes

KEY_OVERRIDE_ENABLE = no

SPLIT_KEYBOARD = yes

ENCODER_ENABLE = yes

DEFERRED_EXEC_ENABLE = no
LTO_ENABLE = yes
VIA_ENABLE = yes

SRC += matrix.c