CUSTOM_MATRIX = lite

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
STENO_ENABLE = no
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = yes
OS_DETECTION_ENABLE = yes

CUSTOM_KEYCODE = no
SERIAL_DRIVER = vendor
KEYBOARD_SHARED_EP = yes

RGBLIGHT_ENABLE = no   # Enable keyboard RGB underglow
WS2812_DRIVER = vendor

RGB_MATRIX_ENABLE = yes   # Enable keyboard RGB per key

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_TIMEOUT = 0
OLED_TRANSPORT = i2c
WPM_ENABLE = yes

KEY_OVERRIDE_ENABLE = no

SPLIT_KEYBOARD = yes

ENCODER_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes	
LTO_ENABLE = yes
VIA_ENABLE = yes

SRC += matrix.c