CUSTOM_MATRIX = lite

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
MOUSEKEY_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

WS2812_DRIVER = vendor

MIDI_ENABLE = yes

OLED_ENABLE = no
OLED_DRIVER = SSD1306
OLED_TRANSPORT = i2c
WPM_ENABLE = yes

KEY_OVERRIDE_ENABLE = no

SPLIT_KEYBOARD = yes

ENCODER_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes
LTO_ENABLE = yes
VIA_ENABLE = yes

SRC += matrix.c